version: '3.7'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - app-network

  php:
    image: php:7.4-fpm
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
